# Generated by Django 5.1.1 on 2024-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255)),
                ('computer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
                ('data_center_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vmware_datacenter', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('technical_contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('support_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('guard', models.CharField(blank=True, max_length=255, null=True)),
                ('application_id', models.CharField(max_length=50)),
                ('application_name', models.CharField(blank=True, max_length=255, null=True)),
                ('a_number', models.CharField(max_length=50)),
                ('deploy_date', models.DateField(blank=True, null=True)),
                ('asset_status', models.CharField(max_length=50)),
            ],
        ),
    ]
