# Generated by Django 5.1.1 on 2024-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='a_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
