# Generated by Django 5.1.1 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0002_alter_asset_a_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='application_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
