# Generated by Django 5.1.1 on 2024-09-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0003_alter_asset_application_id_alter_asset_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
