# Generated by Django 5.1.1 on 2024-09-18 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0004_alter_asset_host_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='host_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
