# Generated by Django 5.1.1 on 2024-09-19 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0005_remove_asset_id_alter_asset_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='aap_patchday',
            fields=[
                ('aap_patch_env', models.CharField(choices=[('TEST / DEV', 'Test and Development'), ('QA / PREPROD', 'Quality Assurance and Pre-Production'), ('PROD', 'Production')], max_length=50, primary_key=True, serialize=False)),
                ('aap_patch_date_january', models.DateField(blank=True, null=True)),
                ('aap_patch_date_february', models.DateField(blank=True, null=True)),
                ('aap_patch_date_march', models.DateField(blank=True, null=True)),
                ('aap_patch_date_april', models.DateField(blank=True, null=True)),
                ('aap_patch_date_may', models.DateField(blank=True, null=True)),
                ('aap_patch_date_june', models.DateField(blank=True, null=True)),
                ('aap_patch_date_july', models.DateField(blank=True, null=True)),
                ('aap_patch_date_august', models.DateField(blank=True, null=True)),
                ('aap_patch_date_september', models.DateField(blank=True, null=True)),
                ('aap_patch_date_october', models.DateField(blank=True, null=True)),
                ('aap_patch_date_november', models.DateField(blank=True, null=True)),
                ('aap_patch_date_december', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AAP Patch Day',
                'verbose_name_plural': 'AAP Patch Days',
                'db_table': 'aap_patchday',
                'ordering': ['aap_patch_env'],
            },
        ),
        migrations.CreateModel(
            name='appid',
            fields=[
                ('appid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=255)),
                ('appowner', models.CharField(max_length=255)),
                ('appcontact', models.CharField(max_length=255)),
                ('appstatus', models.CharField(default='active', max_length=50)),
            ],
            options={
                'verbose_name': 'Application ID',
                'verbose_name_plural': 'Application IDs',
                'db_table': 'appid',
                'ordering': ['appid'],
            },
        ),
        migrations.CreateModel(
            name='patchpeers',
            fields=[
                ('hostname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('peername', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Patch Peer',
                'verbose_name_plural': 'Patch Peers',
                'db_table': 'patchpeers',
                'ordering': ['hostname'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['host_name'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelTable(
            name='asset',
            table='asset',
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('hostname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('detected', models.DateField()),
                ('updated', models.DateField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('healthball', models.URLField(blank=True, default='https://img.shields.io/badge/ok-green.svg', null=True)),
                ('os', models.CharField(choices=[('RHEL', 'Red Hat Enterprise Linux'), ('Oracle Linux', 'Oracle Linux'), ('Rocky Linux', 'Rocky Linux'), ('CentOS', 'CentOS'), ('Ubuntu', 'Ubuntu'), ('Debian', 'Debian'), ('SLES', 'SUSE Linux Enterprise Server'), ('Windows', 'Windows Server'), ('AIX', 'AIX'), ('IBM i', 'IBM i')], max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('os_arch', models.CharField(choices=[('x86_64', '64-bit'), ('i386', '32-bit'), ('ppc64', 'PowerPC 64-bit')], max_length=50)),
                ('os_lastboot', models.CharField(max_length=50)),
                ('os_uptime', models.CharField(max_length=50)),
                ('os_installed', models.DateField(blank=True, null=True)),
                ('os_lastmodified', models.DateTimeField(blank=True, null=True)),
                ('os_eol', models.DateField(blank=True, null=True)),
                ('os_eol_state', models.CharField(blank=True, choices=[('active', 'Active'), ('eol', 'End of Life'), ('eol-extended', 'End of Life Extended Support'), ('eol-unsupported', 'End of Life Unsupported')], max_length=50, null=True)),
                ('aap_autopatch', models.BooleanField(default=False)),
                ('aap_lastpatch', models.CharField(blank=True, max_length=50, null=True)),
                ('aap_nextpatch', models.CharField(blank=True, max_length=50, null=True)),
                ('aap_scheduled_patching', models.JSONField(blank=True, null=True)),
                ('aap_patch_env', models.CharField(blank=True, choices=[('TEST / DEV', 'Test and Development'), ('QA / PREPROD', 'Quality Assurance and Pre-Production'), ('PROD', 'Production')], max_length=50, null=True)),
                ('aap_patch_batch', models.CharField(blank=True, choices=[('1', 'Patch on day one of the patch window'), ('2', 'Patch on day two of the patch window'), ('3', 'Patch on day three of the patch window'), ('4', 'Patch on day four of the patch window')], max_length=50, null=True)),
                ('aap_patch_patchtime', models.CharField(blank=True, choices=[('00', 'Patch at 00:00 and 4 hours ahead'), ('01', 'Patch at 01:00 and 4 hours ahead'), ('02', 'Patch at 02:00 and 4 hours ahead'), ('03', 'Patch at 03:00 and 4 hours ahead'), ('04', 'Patch at 04:00 and 4 hours ahead'), ('05', 'Patch at 05:00 and 4 hours ahead'), ('06', 'Patch at 06:00 and 4 hours ahead'), ('07', 'Patch at 07:00 and 4 hours ahead'), ('08', 'Patch at 08:00 and 4 hours ahead'), ('09', 'Patch at 09:00 and 4 hours ahead'), ('10', 'Patch at 10:00 and 4 hours ahead'), ('11', 'Patch at 11:00 and 4 hours ahead'), ('12', 'Patch at 12:00 and 4 hours ahead'), ('13', 'Patch at 13:00 and 4 hours ahead'), ('14', 'Patch at 14:00 and 4 hours ahead'), ('15', 'Patch at 15:00 and 4 hours ahead'), ('16', 'Patch at 16:00 and 4 hours ahead'), ('17', 'Patch at 17:00 and 4 hours ahead'), ('18', 'Patch at 18:00 and 4 hours ahead'), ('19', 'Patch at 19:00 and 4 hours ahead'), ('20', 'Patch at 20:00 and 4 hours ahead'), ('21', 'Patch at 21:00 and 4 hours ahead'), ('22', 'Patch at 22:00 and 4 hours ahead'), ('23', 'Patch at 23:00 and 4 hours ahead')], max_length=50, null=True)),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverinfo.appid')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'db_table': 'server',
                'ordering': ['os', 'hostname'],
            },
        ),
    ]
