# Generated by Django 5.1.1 on 2024-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0006_aap_patchday_appid_patchpeers_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='environment',
            field=models.CharField(blank=True, choices=[('TEST / DEV', 'Test and Development'), ('QA / PREPROD', 'Quality Assurance and Pre-Production'), ('PROD', 'Production')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='detected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_lastboot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
