# Generated by Django 5.1.1 on 2024-09-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0007_server_environment_alter_server_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='aap_patch_window_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='aap_patch_window_scheduled_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
