# Generated by Django 5.1.1 on 2024-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0008_server_aap_patch_window_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='aap_patch_window_scheduled_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
