# Generated by Django 5.1.1 on 2024-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0010_rename_aap_patch_window_scheduled_url_server_aap_patch_window_scheduled_url_apr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_lastpatch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
