# Generated by Django 5.1.1 on 2024-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverinfo', '0011_server_os_lastpatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
