from django.db import models

# Create your models here.
class application(models.Model):
    Identifier = models.CharField(max_length=255)
    Name = models.CharField(max_length=255)
    Application_Lifecycle_Stage = models.CharField(max_length=255)
    SLA_Applications = models.CharField(max_length=255)
    Crown_Jewel = models.CharField(max_length=255)
    Application_is_owned_by_IT_Vertical = models.CharField(max_length=255)
    Application_has_Service_Owner_Name = models.CharField(max_length=255)
    Application_has_Service_Owner_E_Mail = models.CharField(max_length=255)
    Planned_Retiring_Date = models.CharField(max_length=255)
    Actual_Retiring_Date = models.CharField(max_length=255)
    TIME_Evaluation = models.CharField(max_length=255)
    Justification_for_Tolerate_TIME = models.CharField(max_length=255)
    Application_Subtype = models.CharField(max_length=255)
    Application_has_IT_Service_ApnlId = models.CharField(max_length=255)
    Application_has_IT_Service_IT_Service_Name = models.CharField(max_length=255)
    Description = models.TextField()
    Application_has_primary_Capability = models.CharField(max_length=255)
    Application_has_primary_Capability_IT_Owner = models.CharField(max_length=255)
    Application_has_primary_Capability_Business_Owner = models.CharField(max_length=255)
    Application_has_secondary_Capability = models.CharField(max_length=255)
    Deployment = models.CharField(max_length=255)
    Developed_Purchased = models.CharField(max_length=255)
    Application_has_Business_Releationship_Manager_Name = models.CharField(max_length=255)
    Application_has_Business_Releationship_Manager_E_Mail = models.CharField(max_length=255)
    Application_has_Business_Owner_Name = models.CharField(max_length=255)
    Application_has_Business_Owner_E_Mail = models.CharField(max_length=255)
    Application_has_Technical_Subject_Matter_Expert_Name = models.CharField(max_length=255)
    Application_has_Technical_Subject_Matter_Expert_E_Mail = models.CharField(max_length=255)
    Application_has_Product_Owner_Name = models.CharField(max_length=255)
    Application_has_Product_Owner_E_Mail = models.CharField(max_length=255)
    Application_has_Release_Manager_Name = models.CharField(max_length=255)
    Application_has_Release_Manager_E_Mail = models.CharField(max_length=255)
    Application_has_Application_Subject_Matter_Expert_Name = models.CharField(max_length=255)
    Application_has_Application_Subject_Matter_Expert_E_Mail = models.CharField(max_length=255)
    Application_has_Contract_ContractNumber = models.CharField(max_length=255)
    Application_has_Company_Code_Code = models.CharField(max_length=255)
    Application_has_Company_Code_Name = models.CharField(max_length=255)
    Application_is_used_by_Division = models.CharField(max_length=255)
    Application_is_used_by_Country_Iso = models.CharField(max_length=255)
    Application_is_used_by_Country_Name = models.CharField(max_length=255)
    Origin = models.CharField(max_length=255)
    Recovery_Time_Objective = models.CharField(max_length=255)
    Recovery_Point_Objective = models.CharField(max_length=255)
    Application_requires_Application = models.CharField(max_length=255)
    Application_is_required_by_Application = models.CharField(max_length=255)
    Alias = models.CharField(max_length=255)
    System_of_Record = models.CharField(max_length=255)
    System_of_Record_Source_Date = models.CharField(max_length=255)
    Top_Supporting_Top = models.CharField(max_length=255)
    Application_is_supplied_by_Vendor = models.CharField(max_length=255)
    BRM_Comment = models.CharField(max_length=255)
    configitems = models.JSONField(blank=True,null=True)
    def __str__(self):
        return self.Name
       